global.credit = 0;
ini_open("highscores.ini");
global.pacscore = ini_read_real("highscores", "pacscore", 0);
global.mspacscore = ini_read_real("highscores", "mspacscore", 0);
global.jrpacscore = ini_read_real("highscores", "jrpacscore", 0);
global.pacplusscore = ini_read_real("highscores", "pacplusscore", 0);
global.mspacplusscore = ini_read_real("highscores", "mspacplusscore", 0);
global.jrpacplusscore = ini_read_real("highscores", "jrpacplusscore", 0);
global.pacrandscore  = ini_read_real("highscores", "pacrandscore", 0);
global.mspacrandscore  = ini_read_real("highscores", "mspacrandscore", 0);
global.jrpacrandscore  = ini_read_real("highscores", "jrpacrandscore", 0);
global.pacplusrandscore  = ini_read_real("highscores", "pacplusrandscore", 0);
global.mspacplusrandscore  = ini_read_real("highscores", "mspacplusrandscore", 0);
global.jrpacplusrandscore  = ini_read_real("highscores", "jrpacplusrandscore", 0);
global.hanglyscore = ini_read_real("highscores", "hanglyscore", 0);
global.newscore = ini_read_real("highscores", "newscore", 0);
global.ultrascore = ini_read_real("highscores", "ultrascore", 0);
global.mspmpscore = ini_read_real("highscores", "mspmpscore", 0);
global.pacjrscore = ini_read_real("highscores", "pacjrscore", 0);
global.strangescore = ini_read_real("highscores", "strangescore", 0);
global.hanglyplusscore = ini_read_real("highscores", "hanglyplusscore", 0);
global.newplusscore = ini_read_real("highscores", "newplusscore", 0);
global.ultraplusscore = ini_read_real("highscores", "ultraplusscore", 0);
global.mspmpplusscore = ini_read_real("highscores", "mspmpplusscore", 0);
global.pacjrplusscore = ini_read_real("highscores", "pacjrplusscore", 0);
global.strangeplusscore = ini_read_real("highscores", "strangeplusscore", 0);
global.extendedscore = ini_read_real("highscores", "extendedscore", 0);
global.c64score = ini_read_real("highscores", "c64score", 0);
global.a2600score = ini_read_real("highscores", "a2600score", 0);
global.extendedplusscore = ini_read_real("highscores", "extendedplusscore", 0);
global.c64plusscore = ini_read_real("highscores", "c64plusscore", 0);
global.a2600plusscore = ini_read_real("highscores", "a2600plusscore", 0);
global.champscore = ini_read_real("highscores", "champscore", 0);
global.champplusscore = ini_read_real("highscores", "champplusscore", 0);
global.arrscore = ini_read_real("highscores", "arrscore", 0);
global.arrplusscore = ini_read_real("highscores", "arrplusscore", 0);
global.bleachscore = ini_read_real("highscores", "bleachscore", 0);
global.bleachplusscore = ini_read_real("highscores", "bleachplusscore", 0);
ini_close();


global.game = 0; global.plus = 0; global.rand = 0; global.mode = 0; global.boost = 0;
global.color = 0;
sound_stop(Ghost1);
sound_stop(Ghost2);
sound_stop(Ghost3);
sound_stop(Ghost4);
sound_stop(Ghost5);
sound_stop(Blue);
sound_stop(Flee);
sound_stop(Int);
sound_stop(MsGhost1);
sound_stop(MsGhost2);
sound_stop(MsGhost3);
sound_stop(MsGhost4);
sound_stop(MsGhost5);
sound_stop(MsBlue);
sound_stop(MsFlee);
sound_stop(MsInt1);
sound_stop(MsInt2);
sound_stop(MsInt3);
sound_stop(JrGhost1);
sound_stop(JrGhost2);
sound_stop(JrGhost3);
sound_stop(JrGhost4);
sound_stop(JrGhost5);
sound_stop(JrBlue);
sound_stop(JrFlee);
sound_stop(JrInt1);
sound_stop(JrInt2);
sound_stop(JrInt3);

